version: 2
jobs:
  build:
    docker:
      - image: icddex/php-images:run-tests

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: curl -sS https://getcomposer.org/installer | php
      - run: php composer.phar install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never